---
config:
    MD003:
        style: "atx"
    MD007:
        indent: 3
    MD013:
        line_length: 10000000
        heading_line_length: 70
        code_block_line_length: 10000000
        code_blocks: false
        tables: false
    MD024: false
    MD025:
        front_matter_title:
    MD046:
        style: fenced
globs:
    - README.md
    - 'src/*.md'
    - 'src/**/*.md'
